---
- hosts: all
  remote_user: root
  tasks:
    - name: Install Apache Web Server
      yum:
        name:httpd
        state: latest
    - name: Start Apache Web Server
      sudo: yes
      service:
        enabled: yes
        name: httpd
        state: started    