---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install multiple packages
      when: ansible_distribution == "Ubuntu" and ansible_distribution == "CentOS" and ansible_distribution == "Debian"
      package:
        name: "{{ item }}"
        state: present
      with_items:
       - telnet
       - vim 
       - get 
       - 